name: CI

on:
  pull_request:
    branches: [ main ]

  push:
    branches:
      - main
      - feature/**
      - fix/**
      - hotfix/**

jobs:

  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Validate composer.json
        run: composer validate --strict

  static:
    name: Static Analysis
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress

      - name: PHPStan
        run: composer phpstan

      - name: Coding Style
        run: composer cs-check

  test:
    name: Tests (PHP ${{ matrix.php }})
    needs: static
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4']

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          extensions: intl

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress

      - name: Run tests
        run: composer test

      - name: Run coverage
        if: matrix.php == '8.4'
        run: composer test:coverage

      - name: Upload coverage
        if: matrix.php == '8.4'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/clover.xml